version: '3.8'

services:
  app:
    build: .
    container_name: musicdownloader_app
    restart: always
    expose:
      - "8048"
    env_file:
      - config.env
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: musicdownloader_nginx
    ports:
      - "85:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
